<a href="https://colab.research.google.com/github/PratyushMaharana/pytorch/blob/main/pytorch_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import time

In [ ]:
t=torch.linspace(0,1,5)
n=np.linspace(0,1,5)

In [ ]:
torch.arange(48)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])

In [ ]:
np.arange(48).reshape(3,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [ ]:
a=np.array([1,2])
b=np.array([3,4])

In [ ]:
a*b

array([3, 8])

GENERAL BROADCASTING

In [ ]:
a=np.ones((6,5))
b=np.arange(5).reshape((1,5))

In [ ]:
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
b

array([[0, 1, 2, 3, 4]])

In [ ]:
a*b

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [ ]:
a.shape

(6, 5)

In [ ]:
image=torch.randn((256,256,3))
scale=torch.tensor([0.5,1.5,1,1.5,1,0.5]).reshape((2,1,1,3))

In [ ]:
result=image*scale

In [ ]:
print(scale)

tensor([[[[0.5000, 1.5000, 1.0000]]],


        [[[1.5000, 1.0000, 0.5000]]]])


In [ ]:
print(image)

tensor([[[ 0.4109,  0.8007,  0.7019],
         [ 0.7381,  0.5744,  0.2504],
         [ 0.1000,  2.0635,  0.5596],
         ...,
         [ 0.5591, -0.0685,  0.8792],
         [-0.0868,  0.4903,  0.8218],
         [ 1.6929,  1.2963,  0.0295]],

        [[-0.2281, -1.4024, -2.0451],
         [-0.9394, -0.3812,  0.2583],
         [ 0.6023, -0.4780,  0.7257],
         ...,
         [ 0.5006,  0.6049,  1.4793],
         [ 0.7169, -0.2062, -0.4242],
         [ 0.3063, -1.0788, -0.4371]],

        [[ 2.2452, -0.2963,  0.1217],
         [-0.4868,  0.0660,  0.4692],
         [ 0.7061, -0.2200, -0.3587],
         ...,
         [ 0.3811,  0.2914,  1.0539],
         [-1.0300,  0.4654,  0.8855],
         [-1.2195, -0.8255,  0.3710]],

        ...,

        [[-1.9406,  1.1364,  0.7091],
         [-1.0357,  0.2416, -1.9255],
         [ 0.8803, -0.7085,  1.2594],
         ...,
         [-0.4674,  0.6061,  0.0652],
         [-0.4225,  1.0388,  0.5076],
         [ 0.9824, -0.5741,  0.7140]],

        [[

In [ ]:
result

tensor([[[[ 2.0543e-01,  1.2011e+00,  7.0194e-01],
          [ 3.6903e-01,  8.6159e-01,  2.5037e-01],
          [ 4.9978e-02,  3.0952e+00,  5.5957e-01],
          ...,
          [ 2.7957e-01, -1.0275e-01,  8.7916e-01],
          [-4.3389e-02,  7.3551e-01,  8.2182e-01],
          [ 8.4647e-01,  1.9444e+00,  2.9508e-02]],

         [[-1.1405e-01, -2.1036e+00, -2.0451e+00],
          [-4.6971e-01, -5.7184e-01,  2.5827e-01],
          [ 3.0113e-01, -7.1701e-01,  7.2572e-01],
          ...,
          [ 2.5030e-01,  9.0732e-01,  1.4793e+00],
          [ 3.5847e-01, -3.0929e-01, -4.2420e-01],
          [ 1.5316e-01, -1.6181e+00, -4.3710e-01]],

         [[ 1.1226e+00, -4.4450e-01,  1.2171e-01],
          [-2.4339e-01,  9.8958e-02,  4.6924e-01],
          [ 3.5305e-01, -3.2993e-01, -3.5874e-01],
          ...,
          [ 1.9057e-01,  4.3713e-01,  1.0539e+00],
          [-5.1498e-01,  6.9803e-01,  8.8552e-01],
          [-6.0973e-01, -1.2382e+00,  3.7098e-01]],

         ...,

         [[-9.70

# Operation Across Dimensions
this is so fundamental for pytorch. Obv simple operations can be done one 1 dimensionsal tensors

In [ ]:
t=torch.tensor([0.5,1,3,4])
torch.mean(t), torch.std(t), torch.max(t), torch.min(t)

(tensor(2.1250), tensor(1.6520), tensor(4.), tensor(0.5000))

but suppsose we have 2d tensor ,for ex and want to compute the mean value fo each columns

In [ ]:
t=torch.arange(20,dtype=float).reshape(5,4)

In [ ]:
t[0]

tensor([0., 1., 2., 3.], dtype=torch.float64)

In [ ]:
print(t)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]], dtype=torch.float64)


In [ ]:
torch.mean(t,axis=0).shape

torch.Size([4])

this can be done for higher dimensionally arrays as well

In [ ]:
t=torch.randn(5,256,256,3)

In [ ]:
torch.mean(t,axis=0).shape

torch.Size([256, 256, 3])

take the mean across the color channels

In [ ]:
torch.mean(t,axis=-1).shape

torch.Size([5, 256, 256])

maximum color channel values
this is done all the time in image segementation models

In [ ]:
values , indices = torch.max(t,axis=-1)

In [ ]:
indices

tensor([[[2, 0, 1,  ..., 1, 1, 2],
         [0, 0, 0,  ..., 2, 1, 2],
         [1, 2, 1,  ..., 2, 2, 2],
         ...,
         [0, 0, 2,  ..., 2, 0, 1],
         [2, 2, 0,  ..., 2, 1, 2],
         [1, 2, 1,  ..., 2, 1, 0]],

        [[2, 2, 1,  ..., 0, 1, 2],
         [0, 2, 0,  ..., 0, 0, 1],
         [1, 2, 1,  ..., 1, 2, 1],
         ...,
         [2, 2, 0,  ..., 2, 0, 2],
         [0, 2, 2,  ..., 0, 1, 2],
         [0, 2, 2,  ..., 1, 1, 1]],

        [[0, 0, 2,  ..., 2, 0, 2],
         [0, 1, 1,  ..., 1, 2, 1],
         [1, 1, 1,  ..., 1, 0, 0],
         ...,
         [2, 0, 0,  ..., 1, 1, 1],
         [0, 1, 1,  ..., 2, 0, 0],
         [0, 0, 0,  ..., 0, 0, 0]],

        [[1, 2, 0,  ..., 2, 0, 1],
         [1, 1, 0,  ..., 1, 0, 2],
         [0, 2, 2,  ..., 0, 2, 2],
         ...,
         [1, 0, 0,  ..., 1, 1, 1],
         [2, 2, 2,  ..., 2, 2, 0],
         [1, 1, 1,  ..., 1, 1, 2]],

        [[1, 1, 2,  ..., 1, 1, 2],
         [2, 0, 2,  ..., 1, 1, 1],
         [2, 0, 1,  ..., 2

In [ ]:
x=torch.tensor([[5.,8.],[4.,6.]], requires_grad=True)
y=x.pow(3).sum()
y
x

tensor([[5., 8.],
        [4., 6.]], requires_grad=True)

In [ ]:
y.backward() #compute the gradient
x.grad # print the gradient

tensor([[ 75., 192.],
        [ 48., 108.]])

In [ ]:
x.grad

tensor([[ 75., 192.],
        [ 48., 108.]])

***Any  sort of large matrix multiplication problem is faster with torch tensors that it is with numpy arrays especially when you are running gpu***

In [ ]:
A=torch.randn((1000,1000))
B=torch.randn((1000,1000))

In [76]:
t1=time.perf_counter()
torch.matmul(A,B)
t2=time.perf_counter()
print(t1-t2)

-0.035327280000274186
