<a href="https://colab.research.google.com/github/PratyushMaharana/pytorch/blob/main/pytorch_neural_nets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import torch.nn as nn
from torch.optim import SGD
import numpy as np
import matplotlib.pyplot as plt

In [4]:
x = torch.tensor([[6,2],[5,2],[1,3],[7,6]]).float()
y = torch.tensor([1,5,2,5]).float()
x
y

tensor([1., 5., 2., 5.])

In [5]:
M1 = nn.Linear(2,8,bias=False)
M1

Linear(in_features=2, out_features=8, bias=False)

In [6]:
M1(x)

tensor([[-2.5731,  2.9992,  3.9511,  2.0381, -2.7953, -3.1677,  3.8319, -1.4976],
        [-2.0009,  2.5666,  3.3252,  1.9103, -2.2598, -2.6060,  3.2252, -1.1531],
        [ 0.7175,  1.0379,  0.9195,  2.0345,  0.0911, -0.2580,  0.8939,  0.5097],
        [-1.4256,  4.2388,  4.9685,  4.7082, -2.4953, -3.3244,  4.8215, -0.7031]],
       grad_fn=<MmBackward0>)

In [10]:
M2 = nn.Linear(8,1,bias=False)
M2

Linear(in_features=8, out_features=1, bias=False)

In [11]:
M2(M1(x)).squeeze

<function Tensor.squeeze>

In [12]:
y

tensor([1., 5., 2., 5.])

In [13]:
class myneunets(nn.Module):
  def __init__(self):
    super().__init__()
    self.Matrix1 = nn.Linear(2,8,bias=False)
    self.Matrix2 = nn.Linear(8,1,bias=False)
  def forward(self,x):
    x = self.Matrix1(x)
    x = self.Matrix2(x)
    return x.squeeze()

In [15]:
f = myneunets()
yhat = f(x)
yhat

tensor([-0.7107, -0.6181, -0.3249, -1.1131], grad_fn=<SqueezeBackward0>)